name: Rustdoc
on:
  push:
    branches:
      - master

jobs:
  rustdoc:
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@v1
      - uses: actions/checkout@master
      - name: Build docs
        run: |
          cargo doc --all-features
          cat > target/doc/index.html <<EOF
          <!doctype html>
          <html><head>
            <meta http-equiv="refresh" content="0; URL='simdify/'" />
          </head></html>
          EOF
      - name: Deploy to Github Pages
        uses: crazy-max/ghaction-github-pages@master
        if: success()
        with:
          target_branch: gh-pages
          build_dir: target/doc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PAT: ${{ secrets.ACCESS_TOKEN }}
        # uses: JamesIves/github-pages-deploy-action@master
        # if: success()
        # env:
        #   ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        #   BASE_BRANCH: master
        #   BRANCH: gh-pages
        #   FOLDER: target/doc
